// Common crops & vegetables grown in Cambodia. Users can also type their own.
export const COMMON_CROPS = [
  "Avocado",
  "Durian",
  "Mango",
  "Coconut",
  "Jackfruit",
  "Papaya",
  "Banana",
  "Pineapple",
  "Longan",
  "Lychee",
  "Rambutan",
  "Passion fruit",
  "Lemon",
  "Lime",
  "Orange",
  "Cashew",
  "Cacao",
  "Coffee",
  "Black pepper",
  "Rice",
  "Cassava",
  "Sweet potato",
  "Chili",
  "Tomato",
  "Cucumber",
  "Morning glory",
  "Lemongrass",
  "Ginger",
  "Turmeric",
  "Kaffir lime",
];
